### ISSUE TITLE
If I want to use this model to train my own data set, how should I label the data?

### ISSUE THREAD

**Issue by NuaaWill** [MingtaoFu/gliding_vertex#1]

**Comment by MingtaoFu** [comment]
DOTA's default annotation format is *.txt, which is composed of text lines: `x1, y1, x2, y2, x3, y3, x4, y4, cls, diff`. In this project, we convert the txt annotations to json annotations with `txt2json.py`.
I updated the README.md and added the section `If you want to train with your own data` in it. Please refer to it.

**Comment by MingtaoFu** [comment]
If you need more details, feel free to make additional comments.
