### ISSUE TITLE
reproduce the results on DOTA

### ISSUE THREAD

**Issue by lijain** [MingtaoFu/gliding_vertex#10]
The method you give feels very good. I'm trying to reproduce the results on DOTA。But it didn't turn out very well
mAP: 0.37571084834148033
ap of each class: plane:0.5385116102707004, 
baseball-diamond:0.2727272727272727, 
bridge:0.44082450946597307, 
ground-track-field:0.1341991341991342, 
small-vehicle:0.24204960393608227, 
large-vehicle:0.23971794346542388,
 ship:0.7038695273857871, 
tennis-court:0.5445677486811463,
 basketball-court:0.262269548633185,
 storage-tank:0.09090909090909091, 
soccer-ball-field:0.22112554112554111,
 roundabout:0.20355436306356553,
 harbor:0.6819254239848229, 
swimming-pool:0.6348744724980455, 
helicopter:0.42453693477643495

**Comment by MingtaoFu** [comment]
Yesterday I received a mail that posted a similar issue. Is that you?

**Comment by lijain** [comment]
Yes, I checked it yesterday. But it didn't improve much, so I posted the results and asked the big guy to help me analyze them. Otherwise, I feel stuck here for a long time. Sorry to bother you.

**Comment by MingtaoFu** [comment]
According to your provided visualization result, I think there is no problems with it. I think there is something wrong with evaluation. You can post one of your txt results and your evaluation method, and I will help you check it.

**Comment by lijain** [comment]
首先，感谢你这么耐心的帮我解答。首先我才用的是根据你给的过程，并在google上下载你公布的权重。test中数据的切分也是按照你的prepare.py中来的，就改了一下数据的地址等其他的否没有变。最后将1024x1024剪切图预测的结果是按照DOTA_devkit中的ResultMerge.py中进行合并的，阈值设置的是nms_thresh=0.3。其他的都没有变，现在就想知道为什么和你论文中的结果差距这么大



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mingtao Fu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 上午9:52
收件人:&nbsp;"MingtaoFu/gliding_vertex"<gliding_vertex@noreply.github.com&gt;;
抄送:&nbsp;"利剑"<1632401541@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MingtaoFu/gliding_vertex] reproduce the results on DOTA (#10)





 
According to your provided visualization result, I think there is no problems with it. I think there is something wrong with evaluation. You can post one of your txt results and your evaluation method, and I will help you check it.

**Comment by MingtaoFu** [comment]
The process you described is testing, maybe there is something wrong with evaluation.

**Comment by lijain** [comment]
谢谢你的解答。按照你的意思，我运行的过程是没有错误的，错误是我用错了数据集？其实我就想看下能否复现你论文中的结果，如果可以就好好学习下。
还有一个问题，你说压缩后图片预测结果不好，你说修改最大检测框数，是那个参数？？？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mingtao Fu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 上午10:09
收件人:&nbsp;"MingtaoFu/gliding_vertex"<gliding_vertex@noreply.github.com&gt;;
抄送:&nbsp;"利剑"<1632401541@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MingtaoFu/gliding_vertex] reproduce the results on DOTA (#10)





 
The process you described is testing, maybe there is something wrong with evaluation.

**Comment by MingtaoFu** [comment]
![P0006__1__0___0](https://user-images.githubusercontent.com/9403555/78317745-b37b4a80-7595-11ea-8e3e-31806cfb3629.png)
Your provided visualization seems pretty good, so there is no problems in the outputs of the network.
From it to the final mAP results, there are still several procedures.
1. From Python tensor object to txt file.
2. The validation process reads your txt file and calculate the mAP.

The first point has naturally done by our codes. Plz check whether you modified the project.

**Comment by lijain** [comment]
还是的感谢你这么耐心的详解，我可以确定的说我首先想复现你论文中的精确度。我拿到你的权重然后就按照你的步骤进行测试。你可以给一个你的test测试详细过程吗？比如我的是：先用prepare.py切test(不压缩切和压缩0.5)图1024大小重叠512--&gt;进行预测保存，测试出来后是切片1024图的txt--&gt;对切出来预测的结果进行ResultMerge.py合并nms_thresh=0.3然后拿到整图的预测--&gt;dota评测  是这么一个过程。那块有问题或者不足你帮忙看下，最好能给出你test的详细过程，我只是想简单的复现下结果。麻烦你了

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mingtao Fu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 上午10:30
收件人:&nbsp;"MingtaoFu/gliding_vertex"<gliding_vertex@noreply.github.com&gt;;
抄送:&nbsp;"利剑"<1632401541@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MingtaoFu/gliding_vertex] reproduce the results on DOTA (#10)





 

 Your provided visualization seems pretty good, so there is no problems in the outputs of the network.
 From it to the final mAP results, there are still several procedures.
  
From Python tensor object to txt file.
 
The validation process reads your txt file and calculate the mAP.
  
The first point has naturally done by our codes. Plz check whether you modified the project.

**Comment by MingtaoFu** [comment]
我认为并不是裁剪和拼接的问题，如果您认为是这个问题的话，建议您尝试将拼接完之后的结果重新进行可视化，看是否有问题。

**Comment by lijain** [comment]
好的，我在查看下。不知道你觉得主要的问题在哪呢？？因为我就是按照你给的过程走的，评测也是dota官方给的，你论文中应该也是用dota test的数据测试的吧！所以我感到非常的困惑，才求助下源码的大佬！望你能帮我解决这个问题。



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mingtao Fu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 上午10:58
收件人:&nbsp;"MingtaoFu/gliding_vertex"<gliding_vertex@noreply.github.com&gt;;
抄送:&nbsp;"利剑"<1632401541@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MingtaoFu/gliding_vertex] reproduce the results on DOTA (#10)





 
我认为并不是裁剪和拼接的问题，如果您认为是这个问题的话，建议您尝试将拼接完之后的结果重新进行可视化，看是否有问题。

**Comment by liwenjielongren** [comment]
![image](https://user-images.githubusercontent.com/52265815/78857038-df497500-7a5a-11ea-9450-ae030bcd25ac.png)
请问，我执行prepare.py之后，执行python -m torch.distributed.launch --nproc_per_node=3 tools/test_net.py --config-file configs/glide/dota.yaml命令，结果出现上图的错误是什么原因。

**Comment by lijain** [comment]
I recently reviewed it and felt that my running process is consistent with what you have given. I'd like to ask you whether the map given in your paper is the evaluation result of DOTA test on the official website, or the script you wrote yourself?&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; You said above from the results to the txt file, there are some running programs. Write the predicted tensor to the function of TXT? I see no problem. So I found all the possibilities I thought of, but they still haven't been solved. I still want you to help me.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; I can also send some more test prediction graphs of DOTA. I wonder if this will let you see that my piece is wrong??   

 

 ------------------ 原始邮件 ------------------
  发件人:&nbsp;"Mingtao Fu"<notifications@github.com&gt;;
 发送时间:&nbsp;2020年4月3日(星期五) 上午10:58
 收件人:&nbsp;"MingtaoFu/gliding_vertex"<gliding_vertex@noreply.github.com&gt;;
 抄送:&nbsp;"利剑"<1632401541@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
 主题:&nbsp;Re: [MingtaoFu/gliding_vertex] reproduce the results on DOTA (#10)

 

 

 
我认为并不是裁剪和拼接的问题，如果您认为是这个问题的话，建议您尝试将拼接完之后的结果重新进行可视化，看是否有问题。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

result.rar (216.85M, 2020年05月10日 11:51 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=5c306561a25610c5e64829004734501857530655595050544e03575558195604505148585305511a51085c045903550354055c05613e62450643100d151a1056113058&t=exs_ftn_download&code=c0eaa4b7

**Comment by lijain** [comment]
Hello, author. I wonder if you see the email I sent you. I've also sent you the results of DOTA prediction. If you're busy, it's not right. Could you please send me the 15. TXT documents predicted by your dota? I'll compare myself and find out the problem

**Comment by lijain** [comment]
Who can reproduce the result similar to that given by the author? Please advise me

**Comment by wuhengliangliang** [comment]
您好作者我按照的方法先对labeTxt文件转换为json文件不知道为什么出现了数组越界问题
![image](https://user-images.githubusercontent.com/39480565/80444145-88410c80-8943-11ea-8bea-345c9aa50e69.png)
![image](https://user-images.githubusercontent.com/39480565/80444168-9a22af80-8943-11ea-80a3-51a9fbbc6e4a.png)
希望您百忙之中能解答一下，感激不尽。

**Comment by MingtaoFu** [comment]
@lijain 您好，我检查了一遍之后，项目中确实存在一个问题。就是当你切割时存在缩小的图片时，文件名中会有```0.5```，例如```P1619__0.5__976___0.png```，之前的代码使用```.```来分割文件名，导致文件名错写为```P1619__0```。现在这个问题已经更正，详情在https://github.com/MingtaoFu/gliding_vertex/commit/97e9c5d579ac8bfc3dc9e955a2871139837e03e5 中。另外，我上传了在验证集上的结果并更新了README：```4. Check if you use this project correctly```。您可以用我上传的结果作为对照。

**Comment by MingtaoFu** [comment]
@wuhengliangliang 您好，请您打印一下```line```的内容是什么。

**Comment by lijain** [comment]
这个我自己已经改过了
目前还是不清楚是不是我拼图那块有问题，方便分话可以加下qq？我的是1632401541




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Mingtao Fu"<notifications@github.com&gt;; 
发送时间: 2020年5月5日(星期二) 晚上9:14
收件人: "MingtaoFu/gliding_vertex"<gliding_vertex@noreply.github.com&gt;; 
抄送: "利剑"<1632401541@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [MingtaoFu/gliding_vertex] reproduce the results on DOTA (#10)





 
@lijain 您好，我检查了一遍之后，项目中确实存在一个问题。就是当你切割时存在缩小的图片时，文件名中会有0.5，例如P1619__0.5__976___0.png，之前的代码使用.来分割文件名，导致文件名错写为P1619__0。现在这个问题已经更正，详情在97e9c5d 中。另外，我上传了在验证集上的结果并更新了README：4. Check if you use this project correctly。您可以用我上传的结果作为对照。

**Comment by lijain** [comment]
最后自己经过测试，发现复现的结果与论文中一样
