### ISSUE TITLE
no model file

### ISSUE THREAD

**Issue by 888dahong888** [MingtaoFu/gliding_vertex#12]
I run the training data set of their own, but did not find the output of the model file, only the config directory. Yml, label. Json, log. TXT

**Comment by MingtaoFu** [comment]
What's the meaning of "I run the training data set of their own"?

**Comment by 888dahong888** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Mingtao Fu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月3日(星期五) 下午3:37
收件人:&nbsp;"MingtaoFu/gliding_vertex"<gliding_vertex@noreply.github.com&gt;;
抄送:&nbsp;"拈花一笑"<909480900@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MingtaoFu/gliding_vertex] no model file (#12)





 
What's the meaning of "I run the training data set of their own"?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

i use to myself data set to train，but i not find my model file&nbsp;

**Comment by MingtaoFu** [comment]
Did the training procedure complete?
As you can see in https://github.com/MingtaoFu/gliding_vertex/blob/master/configs/glide/dota.yaml#L52, we save the checkpoint from the 30000th step. Too early models won't be saved.
Maybe you didn't training so many steps. So plz try to change it.
