### ISSUE TITLE
论文复现结果问题

### ISSUE THREAD

**Issue by 0Irene0** [MingtaoFu/gliding_vertex#19]
您好，我用您百度网盘给的权重文件，在验证集上测试了一下结果，map只有42，评价用的是DOTA_devikit 上task1的评价方法。这个结果差的有点大，想问下您可能是哪里出了问题?

**Comment by 0Irene0** [comment]
这个是具体的结果：
map: 0.4212388870789987
classaps:  [58.28427523 36.55961396 45.02162017 26.85095161 34.32367746 51.08855303
 40.5894137  78.9515568  50.85496529 42.28125556 33.37775875 39.59036891
 48.9132584  26.11698019 19.05408157]

**Comment by MingtaoFu** [comment]
您好，我检查了一遍之后，项目中确实存在一个问题。就是当你切割时存在缩小的图片时，文件名中会有```0.5```，例如```P1619__0.5__976___0.png```，之前的代码使用```.```来分割文件名，导致文件名错写为```P1619__0```。现在这个问题已经更正，详情在https://github.com/MingtaoFu/gliding_vertex/commit/97e9c5d579ac8bfc3dc9e955a2871139837e03e5 中。另外，我上传了在验证集上的结果并更新了README：```4. Check if you use this project correctly```。您可以用我上传的结果作为对照。
