### ISSUE TITLE
导入包错误

### ISSUE THREAD

**Issue by zhang295498** [MingtaoFu/gliding_vertex#23]
运行test_net.py时，出现以下错误：
/home/zhaolei/.conda/envs/torch-1.4/bin/python3 /media/zhaolei/ubuntu18.04/torch_code/gliding_vertex-master/maskrcnn_benchmark/layers/nms.py
Traceback (most recent call last):
  File "/media/zhaolei/ubuntu18.04/torch_code/gliding_vertex-master/maskrcnn_benchmark/layers/nms.py", line 2, in <module>
    from ._utils import _C
ImportError: attempted relative import with no known parent package

Process finished with exit code 1

请问如何解决？

**Comment by MingtaoFu** [comment]
The project is based on Maskrcnn Benchmark. Please follow its instructions to prepare the environment.
This problem is caused by not compiling the dependencies written in C++ such as nms.
