### ISSUE TITLE
mAP计算以及可视化

### ISSUE THREAD

**Issue by 2018loveyyq** [MingtaoFu/gliding_vertex#25]
你好，我想问一下通过test_net.py得到的.txt文件怎么计算mAP,以及每一个类别的AP,我运行之后的得到的结果如下图：
![image](https://user-images.githubusercontent.com/38448650/89114444-fbac6a00-d4ae-11ea-93e4-bd07465e37b4.png)
但是results目录里面是空的，还有怎么将运行的结果可视化，就是像您图片显示的那样在图片上显示对应的框，新手请求帮助，谢谢。

**Comment by MingtaoFu** [comment]
About the computation of mAP, please refer to https://github.com/CAPTAIN-WHU/DOTA_devkit/tree/99388551054be9a6dabb01c8bb2a7eb562d57b4f

**Comment by MingtaoFu** [comment]
The code of visualization is here: https://github.com/MingtaoFu/gliding_vertex/blob/master/tools/inference.py

**Comment by 2018loveyyq** [comment]
OK，Thanks for your reply.I have got the visualization results.
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "MingtaoFu/gliding_vertex"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月10日(星期一) 晚上6:56
收件人:&nbsp;"MingtaoFu/gliding_vertex"<gliding_vertex@noreply.github.com&gt;;
抄送:&nbsp;"十二"<2539372545@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [MingtaoFu/gliding_vertex] mAP计算以及可视化 (#25)





 
Please refer to https://github.com/CAPTAIN-WHU/DOTA_devkit/tree/99388551054be9a6dabb01c8bb2a7eb562d57b4f
