### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by xs-trinity-lwei** [MingtaoFu/gliding_vertex#3]
Hey,Mingtao.When I run ‘prepare.py’, I am prompted that the module‘DOTA_devkit’ cannot be found.I've seen it in the folder 'maskrcnn_benchmark'. Do I need to copy it out?if i use the pascalvoc
datasets ,what should i do to run for it.

**Comment by MingtaoFu** [comment]
1. About the `DOTA_devkit`. Have you added the folder `maskrcnn_benchmark` into `$PYTHONPATH`? If the error still exists, please post the stderror output.
2. I updated the README.md and added the section If you want to train with your own data in it. Please refer to it.

**Comment by xs-trinity-lwei** [comment]
@MingtaoFu .I solved the above problem. But there are new problems. My pytorch version is 1.2.0, cuda version is 9.0, cudnn version is 7.0, but it always reports 'torch.jit' error when I train. After installing a higher version of pytorch , Apex does not seem to support cuda9.0. The version problem is too troublesome. Do you have more detailed version dependencies?

**Comment by xs-trinity-lwei** [comment]
Overall, I followed the version required in your instructions, but it still has some glitches. I think these are caused by the version.

**Comment by xs-trinity-lwei** [comment]
This is my python list：
apex (0.1)
apturl (0.5.2)
beautifulsoup4 (4.4.1)
blinker (1.3)
Brlapi (0.6.4)
cffi (1.12.3)
chardet (2.3.0)
checkbox-support (0.22)
chrome-gnome-shell (0.0.0)
cloudpickle (1.2.2)
command-not-found (0.3)
cryptography (1.2.3)
cycler (0.10.0)
Cython (0.29.13)
dask (2.9.1)
decorator (4.4.1)
defer (1.0.6)
feedparser (5.1.3)
guacamole (0.9.2)
html5lib (0.999)
httplib2 (0.9.1)
idna (2.0)
Jinja2 (2.8)
kiwisolver (1.1.0)
language-selector (0.1)
louis (2.6.4)
lxml (3.5.0)
Mako (1.0.3)
MarkupSafe (0.23)
maskrcnn-benchmark (0.1, /home/xxx/Desktop/gliding_vertex)
matplotlib (3.0.0)
networkx (2.4)
numpy (1.18.1)
oauthlib (1.0.3)
onboard (1.2.0)
opencv-python (4.1.1.26)
padme (1.1.1)
pexpect (4.0.1)
Pillow (6.1.0)
pip (8.1.1)
plainbox (0.25)
protobuf (3.11.2)
ptyprocess (0.5)
pyasn1 (0.1.9)
pycocotools (2.0.0)
pycparser (2.19)
pycups (1.9.73)
pycurl (7.43.0)
pygobject (3.20.0)
PyJWT (1.3.0)
pyparsing (2.4.2)
python-apt (1.1.0b1+ubuntu0.16.4.8)
python-dateutil (2.8.0)
python-debian (0.1.27)
python-systemd (231)
PyWavelets (1.1.1)
pyxdg (0.25)
PyYAML (5.3.1)
reportlab (3.3.0)
requests (2.9.1)
scikit-image (0.14.0)
scipy (1.4.1)
sessioninstaller (0.0.0)
setuptools (44.0.0)
Shapely (1.6.4.post2)
six (1.13.0)
ssh-import-id (5.5)
system-service (0.3)
tensorboardX (2.0)
toolz (0.10.0)
torch (1.2.0)
torchvision (0.5.0)
tqdm (4.35.0)
ubuntu-drivers-common (0.0.0)
ufw (0.35)
unattended-upgrades (0.1)
unity-scope-calculator (0.1)
unity-scope-chromiumbookmarks (0.1)
unity-scope-colourlovers (0.1)
unity-scope-devhelp (0.1)
unity-scope-firefoxbookmarks (0.1)
unity-scope-gdrive (0.7)
unity-scope-manpages (0.1)
unity-scope-openclipart (0.1)
unity-scope-texdoc (0.1)
unity-scope-tomboy (0.1)
unity-scope-virtualbox (0.1)
unity-scope-yelp (0.1)
unity-scope-zotero (0.1)
urllib3 (1.13.1)
usb-creator (0.3.0)
wheel (0.29.0)
xdiagnose (3.8.4.1)
xkit (0.0.0)
XlsxWriter (0.7.3)
yacs (0.1.6)

**Comment by MingtaoFu** [comment]
Could you please post complete error information?

**Comment by xs-trinity-lwei** [comment]
@MingtaoFu here is the complete error information:
Traceback (most recent call last):
  File "tools/train_net.py", line 15, in <module>
    from maskrcnn_benchmark.data import make_data_loader
  File "/home/xs-trinity/Desktop/gliding_vertex/maskrcnn_benchmark/data/__init__.py", line 2, in <module>
    from .build import make_data_loader
  File "/home/xs-trinity/Desktop/gliding_vertex/maskrcnn_benchmark/data/build.py", line 11, in <module>
    from . import datasets as D
  File "/home/xs-trinity/Desktop/gliding_vertex/maskrcnn_benchmark/data/datasets/__init__.py", line 2, in <module>
    from .coco import COCODataset
  File "/home/xs-trinity/Desktop/gliding_vertex/maskrcnn_benchmark/data/datasets/coco.py", line 3, in <module>
    import torchvision
  File "/usr/local/lib/python3.5/dist-packages/torchvision/__init__.py", line 3, in <module>
    from torchvision import models
  File "/usr/local/lib/python3.5/dist-packages/torchvision/models/__init__.py", line 5, in <module>
    from .inception import *
  File "/usr/local/lib/python3.5/dist-packages/torchvision/models/inception.py", line 65, in <module>
    class Inception3(nn.Module):
  File "/usr/local/lib/python3.5/dist-packages/torchvision/models/inception.py", line 182, in Inception3
    @torch.jit.unused
AttributeError: module 'torch.jit' has no attribute 'unused'
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/torch/distributed/launch.py", line 246, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/torch/distributed/launch.py", line 242, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'tools/train_net.py', '--local_rank=0', '--config-file', 'configs/glide/dota.yaml']' returned non-zero exit status 1

**Comment by MingtaoFu** [comment]
Please try to install pytorch-nightly.

**Comment by xs-trinity-lwei** [comment]
Which version of the preview do I need to install？

**Comment by MingtaoFu** [comment]
pytorch-nightly-1.2.0.dev20190704

**Comment by missFuture** [comment]
> pytorch-nightly-1.2.0.dev20190704
Hi, Mingtao, I just can't find this package from conda source, i can only find the version of 1.0.0, could please tell me where to find it and install it(pytorch-nightly 1.2.0)?
[conda source:http](//topurl.cn/2GG)
