### ISSUE TITLE
How to use Light Head?

### ISSUE THREAD

**Issue by ZhWL123456** [MingtaoFu/gliding_vertex#36]
I have read this paper and find there is the experiment which uses light head, but i cant find out which code is for setting this! Could anyone give me some helps? And also, there are four kinds of class in "./maskrcnn_benchmark/modeling/roi_heads/box_headroi_box_feature_extractors.py " , if there anyone know the different meaning of them.
![image](https://user-images.githubusercontent.com/31128691/97128205-b4b0d680-1776-11eb-82a1-6649c63b0bb4.png)

**Comment by MingtaoFu** [comment]
This repo only contains our own method, please implement by yourself if you want to use light-head in it. According to my experience, light-head architechture does not work well here.

**Comment by ZhWL123456** [comment]
> This repo only contains our own method, please implement by yourself if you want to use light-head in it. According to my experience, light-head architechture does not work well here.

I got it~ Thank u very much!
