### ISSUE TITLE
order of four vertices

### ISSUE THREAD

**Issue by wangyalong123** [MingtaoFu/gliding_vertex#6]
前辈你好，看到了你的文章，感觉思路很好，也非常感谢你的贡献。但是，我现在有一个问题没有弄明白。你在引言中说到了，直接回归回归四边形的顶点会出现点的顺序的混乱的问题，所以我在你的文章中没有发现具体的在那个地方对这个问题进行了解决，因为只按照图2中的计算方法，如果矩形进行顺时针旋转，那么举行的左上角顶点会成为v1，如果进行逆时针选装的话，矩形的右上角顶点会变成v1。我不知到是你在文章中没有提到，还是我没有找到。如果您没有解决方法的话，我是不是就可以理解为实验效果超越了直接四个顶点回归，而没有解决它的这个问题。非常希望您能回复我。

**Comment by MingtaoFu** [comment]
您好，我其实没有太明白您的描述，因为我们的方法似乎和旋转没啥关系。其实根据摘要您可以看到，我们是使用这种表示方法解决了倾斜物体的歧义问题，而水平的物体会有点问题，庆幸的是水平物体我们很好解决，于是我们使用了选择机制来进行弥补。反观直接预测顶点的方法，倾斜的物体是不太好进行弥补的。

**Comment by wangyalong123** [comment]
谢谢您的回答，可能是我描述的有点问题。您主页的邮箱是您使用的吗，我可以通过邮箱想你详细在解释下。

**Comment by MingtaoFu** [comment]
是的
